---
- hosts: rasp
  become: yes

  vars_files:
  - group_vars/all/all.yml
  - group_vars/zigbee2mqtt.yml
  - group_vars/homeassistant.yml

  roles:
    - role: base
    - role: docker
    - role: homeassistant
